<?php

namespace App\Http\Requests;

use App\Rules\SeriaRule;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class CategoryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    protected function prepareForValidation()
    {
        $this->merge([
           'slug' => '551520',
        ]);
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'name' => 'required|min:4|max:255',
//            'slug' => [Rule::in([1,2,3,4,5]),new SeriaRule()],
        ];
    }
    public function messages()
    {
        return [
          'name.min' => 'Поле :attribute не должно быть короче :min-x символов',
          'name.max' => 'Имя категории :attribute  не должно быть длинее 255 символов',
          'name.required' => 'Обязательное поле',
        ];
//        return parent::messages(); // TODO: Change the autogenerated stub
    }
    public function attributes()
    {
        return[
          'name' => 'название категории'
        ];
    }


}
